### ISSUE TITLE
[#US1] [#TASK12] APP - Implementar API no aplicativo, deixando-o cadastro com questionários funcional (Permitindo inserir cadastro de usuário principal)

### ISSUE THREAD

**Issue by brenda2s** [Corona-Track/app-mobile#14]
- OK - Configurar o Login no firebase
- OK - Alterar (url do firebase do projeto)
- OK - Testar o login
- OK - Salvar dados (Perfil Essencial) dados obrigatório do cadastro

*Pontos de Atenção*
- O Login do usuário será o e-mail informado
- Não poderá ter login ou seja (e-mail) duplicado na base de dados
- Não poderá ter CPF duplicado na base de dados

*Pontos levantados na reunião (17/04) 14:30:*
- Incluir validação do CPF *sem ser do governo*
- Incluir validação se CPF existe, se sim não deixar cadastrar novamente
- Incluir validação se e-mail existe, se sim pedir para usuario efeturar o login, pois já está cadastrado
- Se CPF ou E-mail não forem válidos não permitir continuar
- Incluir loading no botão continuar da tela de comorbidades
- Arrumar Layout IOS
- Incluir margin nas telas de cadastro finalizado porque os botoes estão grudados

**Comment by brunoksato** [comment]
Feito na #47
