### ISSUE TITLE
[#US2] [#TASK9] APP - Criar tela de detalhamento/descrição do Perfil (Verde / Amarelo / Vermelho)

### ISSUE THREAD

**Issue by brenda2s** [Corona-Track/app-mobile#43]
- Verificar problema de (Erro Randon)

Acessar o seguinte link p/ + detalhes das telas: https://www.figma.com/file/kChBX6Nr1R1wUQWexe8ody/Coronatrack-V1-(Jur%C3%ADdico)?node-id=1864%3A61
![image](https://user-images.githubusercontent.com/12814438/79510806-6e82f980-8014-11ea-8202-a2820586358f.png)
![image](https://user-images.githubusercontent.com/12814438/79510815-75117100-8014-11ea-9bd8-ef374a7dd9ea.png)

![image](https://user-images.githubusercontent.com/12814438/79510762-5dd28380-8014-11ea-8f5e-13d38cdbdafc.png)

**Comment by rorlf** [comment]
Pull request feito.
