### ISSUE TITLE
[#US1] [#TASK7] APP - Criar telas de formulário do cadastro no aplicativo com telas Questionário (Perguntas Essenciais)

### ISSUE THREAD

**Issue by brenda2s** [Corona-Track/app-mobile#9]

**Comment by lourencogtac** [comment]
Estive atuando na v0 até ontem (12/4/2020)

**Comment by lourencogtac** [comment]
Houveram alterações na v1:

* Mudança de conteúdos de telas;
* Fluxos diferenciados para indivíduos contaminados ou não;
* Mudança de tela de medicamentos para perfil preventivo;
* Adição de disclaimer inicial;
* Adição de conteúdo de texto para entender o que significa o perfil de risco;
* Verificação se perfil vinculado será aplicado.
